# Generated by Django 4.2.18 on 2025-02-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('price', models.CharField(max_length=50, verbose_name='Цена билета')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Картинка фильма')),
            ],
        ),
    ]
