# Generated by Django 4.2.18 on 2025-02-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='image_url',
        ),
    ]
