# Generated by Django 4.2.18 on 2025-02-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_movie_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
